version: '3.8'
services:
  runner:
    image: tcardonne/github-runner:latest
    environment:
      RUNNER_NAME: "Blabell Staging Runner Agent"
      RUNNER_REPOSITORY_URL: "https://github.com/Blabell-Technologies"
      RUNNER_LABELS: "blabell-stg"
      RUNNER_TOKEN: $RUNNER_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
